### ISSUE TITLE
Missing CSS for images included in posts

### ISSUE THREAD

**Issue by AppSecAmael** [Softorage/HugoTheme-VibrantShadows#10]
Hello, 

I tried to include an image directly in a post and saw that the resulting img tag had no CSS/style tags associated. Looking at your main.scss file I see that there's no default styling either for HTML <img> tags. I'm wondering if it would be a good idea to add a styling that would limit images to 100% width ? No idea about side effects on other components.

```CSS
img {
    max-width: 100%;
}
```

Thanks for your feedback :)

**Comment by AppSecAmael** [comment]
For your information I solved this by adding two shortcodes allowing to resize to max-with or a specific size. 

layouts/shortcodes/image-resize.html : 
```html
{{ $imagename := (.Get 0) }}
{{ $options := (.Get 1) }}
{{ with .Page }}
    {{ $image := .Resources.GetMatch $imagename }}
    {{ with ($image.Resize $options) }}
        <img width="{{ .Width }}px" height="{{ .Height }}px" src="{{ .RelPermalink }}" alt="{{  $imagename }}" style="display: block; margin-left: auto; margin-right: auto;">
        <br />
    {{ end }}
{{ end }}
``` 

layouts/shortcodes/image-maxwitdh.html : 
```html
{{ $imagename := (.Get 0) }}
{{ with .Page }}
  {{ $image := .Resources.GetMatch $imagename }}
  {{ with $image }}
      <img style="max-width: 100%;" src="{{ .RelPermalink }}" alt="{{  $imagename }}">
      <br />
  {{ end }}
{{ end }}

```

These codes are adapted to page-bundles and not simple pages, it helps in content organization.

**Comment by SanmayJoshi** [comment]
Hello @AppSecAmael ,

Thanks for the input. I would recommend to use Hugo's built-in shortcode : `figure` when inserting images in a post. I have updated the README.md to briefly describe the same. It is reproduced below:

### Shortcodes
Shortcodes is a feature in Hugo that allows to insert text after performing prespecified complex tasks when writing posts. Let's take example of `figure` shortcode provided by Hugo. When writing a post, say you want to include an image. In this case, you can simply include the shortcode `figure` at the place in post where you want the image to be included. Example syntax of a typical post file located in content directory/folder,

```
title: "Title of Post"
.
.
other frontmatter here
.
.
---

This is the sample post and below is the image that we are inserting:
{{< figure class="max-width" src="/path/to/image/relative/to/root/" alt="Text to show when image is unable to load for some reason" >}}

Rest of the post...
```

 Note that this is just an example, and `figure` shortcode comes with more options.

Hugo's default Shortcodes:
1.  **figure** (Used to include image in a post)  
    Options:
      1.  **class** *(Type: String | Accepts value: all bootstrap classes | Optional)*  
          Takes all bootstrap classes as values. However, it is recommended to use only for width/height setting and margin adjustment by using the bootstrap classes.  
          Width: mw-100, w-25, w-50, w-75, w-100,  
          Height: mh-100, h-25, h-50, h-75, h-100.
      2.  **src** *(Type: String | Accepts value: Relative URL | Required)*  
          The Relative or Absolute URL to image under consideration. Make sure that Relative URL starts with `/` and is written relative to root of the website.
      3.  **alt** *(Type: String | Accepts value: Any text | Optional)*  
          Text to show when image is unable to load for some reason. In absence of `alternate text`, `caption` is used as a fall-back.
      4.  **link** *(Type: String | Accepts value: Absolute URL | Optional)*  
          URL of hyperlink for the image, if so desired.
      5.  **target** *(Type: String | Accepts value: _blank/_self/_parent/_top | Optional)*  
          Optional target attribute for the URL if link parameter is set. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#target
      6.  **rel** *(Type: String | Accepts value: _blank | Optional)*  
          Optional rel attribute for the URL if link parameter is set. See https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel for allowed values (refer `<a>` only).
      7.  **title** *(Type: String | Accepts value: Any text | Optional)*  
          Title to the caption of the image. Caption appear below the image.
      8.  **caption** *(Type: String | Accepts value: Any text | Optional)*  
          Caption text for the image. Caption appear below the image.
      9.  **height** *(Type: Integer | Accepts value: pixels | Optional)*  
          Height attribute of the image.
      10. **width** *(Type: Integer | Accepts value: pixels | Optional)*  
          Width attribute of the image.
      11. **loading** *(Type: String | Accepts value: eager/lazy | Optional)*  
          Loading attribute of the image.  
          eager: Default. Loads an image immediately  
          lazy: Defer loading of images until some conditions are met. See https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading#loading_attribute
      12. **attr** *(Type: String | Accepts value: Any text | Optional)*  
          Image attribution text. Markdown within the value of attr will be rendered.
      13. **attrlink** *(Type: String | Accepts value: Absolute URL | Optional)*  
          If the attribution text needs to be hyperlinked, URL of the destination.

    Example usage,
    ```
    {{< figure class="max-width" src="/images/my-flower-pot.png" alt="My Flower Pot" link="https://examplewebsite.com/flower-pots-for-sale/" title="High Quality Flower Pot" caption="Flower Pot with highest quality Lily and Rose flowers, and black soil pot. Might prove to be the perfect gift!" attr="image by my wife" attrlink="https://examplesite.com/my-wife-photography/" >}}
    ```
2. See https://gohugo.io/content-management/shortcodes/#use-hugos-built-in-shortcodes for a list of all shortcodes provided by Hugo
