### ISSUE TITLE
How to enable Paginator with theme? 

### ISSUE THREAD

**Issue by kpbird** [Softorage/HugoTheme-VibrantShadows#2]

**Comment by SanmayJoshi** [comment]
Hi @kpbird 👋

I haven't added Paginator functionality yet. (Don't remember why though, since it's trivial 🤔). I haven't yet played with Pagination in Hugo. I would start work on it, though, due to my studies, this may take a little bit of time. Feel free to submit a PR though!

**Comment by SanmayJoshi** [comment]
Added via db8aa2e156b1c43163425bfd0cd576de251fa681

An additional feature in the same commit: *Infinite Scroll*
