### ISSUE TITLE
Missing <meta charset> attribute

### ISSUE THREAD

**Issue by AppSecAmael** [Softorage/HugoTheme-VibrantShadows#6]
Hello, 

the templates are missing the `<meta charset="UTF-8">` attribute, disrupting non-ascii characters like [ “ ] [→]... Adding this attribute manually fixes the broken behaviour.

Source file : `layouts\partials\head.html` 
Line to add : `<meta charset="UTF-8">` 

Thanks for taking this in account,
Best regards,

**Comment by SanmayJoshi** [comment]
I hadn't worked on the theme since long so I missed it, but the tag is present in layouts/partials/seo.html . Whether the tag should be included in head since it is essential or should be kept in seo.html since it forms part of SEO is another question that I am open to have a discussion on.

Will be removing the tag from head.html for now. Neverthless thanks for the interest @amael-heiligtag !

**Comment by AppSecAmael** [comment]
Indeed, I can see the tag in the seo part. I missed it as I deactivated seo for my internal website without looking at the seo.html file. I think this tag (along with viewport, X-UA-compatible and title) should not be part of the seo file as they are not seo related - they affect site display for endusers. 

The other tags (description, jsonLD, canonical...) are indeed seo related and should stay there.

I'll let you decide if and what you want to do with this, switching seo on and disabling all subitems solved the issue for me :)

**Comment by SanmayJoshi** [comment]
> I think this tag (along with viewport, X-UA-compatible and title) should not be part of the seo file as they are not seo related - they affect site display for endusers.
> 
> The other tags (description, jsonLD, canonical...) are indeed seo related and should stay there.

[Moved `meta` `charset`, `http-equiv`, `viewport` tags along with `title` tag to head.html from seo.html layout file](https://github.com/Softorage/HugoTheme-VibrantShadows/commit/59d54e67ed0568d5514ead4a0399d273da50ca4d). I have kept the `meta title` tag in seo.html layout though.

**Comment by AppSecAmael** [comment]
Thanks :)
