### ISSUE TITLE
Execute of template failed :  can’t evaluate field .Params.image.alt

### ISSUE THREAD

**Issue by AppSecAmael** [Softorage/HugoTheme-VibrantShadows#9]
Hello, 

I couldn't figure this one out : it's possible to use images in your templates but then the template searches for an "image.alt" property. How are we supposed to set this up in a markdown file ? 

I tried different methods to setup a `Params.image` and a `.Params.image.alt` together but I'm always getting an error. Is it even possible ? Example :
```
image: "/img/posts/my-post-logo.png"
image.alt: "This is the replacement text"
```

Error :
```
ERROR 2022/08/08 17:05:59 Rebuild failed: failed to render pages: render of "home" failed: "C:\mysite\themes\HugoTheme-VibrantShadows\layouts\index.html:44:90": execute of template failed at <.Params.image.alt>: can’t evaluate field alt in type string
```

**Comment by SanmayJoshi** [comment]
Hmm...

Not sure how it slipped through when I was writing docs. Rectifying it would probably introduce some breaking changes.

I'm thinking of making it like:
```yaml
image:
  src: "https://source.url.to.image"
  alt: "Alternative text"
```

The layout would then read `.Params.image.src` and `.Params.image.alt`. This approach would also allow to add other attributes in future in case they get introduced in newer HTML versions (`lazyloading`).

**Comment by AppSecAmael** [comment]
While working at this one I'd love to have a way to configure the height of these images. 320px is quite big and it's the only reason I have to keep my fork ;)

**Comment by SanmayJoshi** [comment]
Hi @AppSecAmael ,

I've updated the theme to use a changed syntax for `image` in the front-matter. Check out the README.md for updated docs. Would love to have your view.

**Comment by AppSecAmael** [comment]
Hello, 

nice work thanks ! I managed to make this work by using a different syntax for the thumbnail size :
`    thumbnailSize: "100 px"`

instead of : 
`  thumbnailSize: [6.25, "rem"]`

The latter one was generating an HTML file with an incorrect value including brackets :
`<img src="/img/posts/my-image.png" height="[6.25 rem]" alt="Logo alternative text">`

Have I done something incorrect or is this a mistake in the Readme file ?

Great theme, again :)

**Comment by SanmayJoshi** [comment]
Thanks a lot for your active participation! 🙏

I've fixed this issue along with squashing some other bugs that introduced a few layout breakages. The docs have also been updated.

So, will be closing this issue. Again, thanks!
